package Pojo;
// Generated Sep 10, 2015 3:19:42 PM by Hibernate Tools 4.3.1



/**
 * FichaPregunta generated by hbm2java
 */
public class FichaPregunta  implements java.io.Serializable {


     private int idFichaInt;
     private Ficha ficha;
     private PreguntEntrenar preguntEntrenar;

    public FichaPregunta() {
    }

    public FichaPregunta(int idFichaInt, Ficha ficha, PreguntEntrenar preguntEntrenar) {
       this.idFichaInt = idFichaInt;
       this.ficha = ficha;
       this.preguntEntrenar = preguntEntrenar;
    }
   
    public int getIdFichaInt() {
        return this.idFichaInt;
    }
    
    public void setIdFichaInt(int idFichaInt) {
        this.idFichaInt = idFichaInt;
    }
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }
    public PreguntEntrenar getPreguntEntrenar() {
        return this.preguntEntrenar;
    }
    
    public void setPreguntEntrenar(PreguntEntrenar preguntEntrenar) {
        this.preguntEntrenar = preguntEntrenar;
    }




}


