package Pojo;
// Generated 24/07/2015 12:27:41 PM by Hibernate Tools 3.6.0



/**
 * Fichainterrogacion generated by hbm2java
 */
public class Fichainterrogacion  implements java.io.Serializable {


     private int idFichaInt;
     private Ficha ficha;
     private Interrogacion interrogacion;

    public Fichainterrogacion() {
    }

    public Fichainterrogacion(int idFichaInt, Ficha ficha, Interrogacion interrogacion) {
       this.idFichaInt = idFichaInt;
       this.ficha = ficha;
       this.interrogacion = interrogacion;
    }
   
    public int getIdFichaInt() {
        return this.idFichaInt;
    }
    
    public void setIdFichaInt(int idFichaInt) {
        this.idFichaInt = idFichaInt;
    }
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }
    public Interrogacion getInterrogacion() {
        return this.interrogacion;
    }
    
    public void setInterrogacion(Interrogacion interrogacion) {
        this.interrogacion = interrogacion;
    }




}


