package Pojo;
// Generated 22/07/2015 06:58:23 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Interrogacion generated by hbm2java
 */
public class Interrogacion  implements java.io.Serializable {


     private int idInt;
     private Testemparejamiento testemparejamiento;
     private Date fecha;
     private Set fichainterrogacions = new HashSet(0);

    public Interrogacion() {
    }

	
    public Interrogacion(int idInt, Testemparejamiento testemparejamiento, Date fecha) {
        this.idInt = idInt;
        this.testemparejamiento = testemparejamiento;
        this.fecha = fecha;
    }
    public Interrogacion(int idInt, Testemparejamiento testemparejamiento, Date fecha, Set fichainterrogacions) {
       this.idInt = idInt;
       this.testemparejamiento = testemparejamiento;
       this.fecha = fecha;
       this.fichainterrogacions = fichainterrogacions;
    }
   
    public int getIdInt() {
        return this.idInt;
    }
    
    public void setIdInt(int idInt) {
        this.idInt = idInt;
    }
    public Testemparejamiento getTestemparejamiento() {
        return this.testemparejamiento;
    }
    
    public void setTestemparejamiento(Testemparejamiento testemparejamiento) {
        this.testemparejamiento = testemparejamiento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getFichainterrogacions() {
        return this.fichainterrogacions;
    }
    
    public void setFichainterrogacions(Set fichainterrogacions) {
        this.fichainterrogacions = fichainterrogacions;
    }




}


