package Pojo;
// Generated 22/07/2015 07:29:31 PM by Hibernate Tools 3.6.0



/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private int idItem;
     private Pregunta pregunta;
     private String nombreItem;
     private byte[] imgItem;
     private int traduccion;

    public Item() {
    }

    public Item(int idItem, Pregunta pregunta, String nombreItem, byte[] imgItem, int traduccion) {
       this.idItem = idItem;
       this.pregunta = pregunta;
       this.nombreItem = nombreItem;
       this.imgItem = imgItem;
       this.traduccion = traduccion;
    }
   
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public String getNombreItem() {
        return this.nombreItem;
    }
    
    public void setNombreItem(String nombreItem) {
        this.nombreItem = nombreItem;
    }
    public byte[] getImgItem() {
        return this.imgItem;
    }
    
    public void setImgItem(byte[] imgItem) {
        this.imgItem = imgItem;
    }
    public int getTraduccion() {
        return this.traduccion;
    }
    
    public void setTraduccion(int traduccion) {
        this.traduccion = traduccion;
    }




}


