package Pojo;
// Generated 23/07/2015 06:24:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idPregunta;
     private Test test;
     private Concepto concepto;
     private String descripcion;
     private double peso;
     private boolean estado;
     private Set items = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int idPregunta, Test test, Concepto concepto, String descripcion, double peso, boolean estado) {
        this.idPregunta = idPregunta;
        this.test = test;
        this.concepto = concepto;
        this.descripcion = descripcion;
        this.peso = peso;
        this.estado = estado;
    }
    public Pregunta(int idPregunta, Test test, Concepto concepto, String descripcion, double peso, boolean estado, Set items) {
       this.idPregunta = idPregunta;
       this.test = test;
       this.concepto = concepto;
       this.descripcion = descripcion;
       this.peso = peso;
       this.estado = estado;
       this.items = items;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPeso() {
        return this.peso;
    }
    
    public void setPeso(double peso) {
        this.peso = peso;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


