package Pojo;
// Generated Sep 10, 2015 3:19:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PreguntEntrenar generated by hbm2java
 */
public class PreguntEntrenar  implements java.io.Serializable {


     private int idInt;
     private Entrenamiento entrenamiento;
     private Date fecha;
     private int valor;
     private int incorrecto;
     private Set fichaPreguntas = new HashSet(0);

    public PreguntEntrenar() {
    }

	
    public PreguntEntrenar(int idInt, Entrenamiento entrenamiento, Date fecha, int valor, int incorrecto) {
        this.idInt = idInt;
        this.entrenamiento = entrenamiento;
        this.fecha = fecha;
        this.valor = valor;
        this.incorrecto = incorrecto;
    }
    public PreguntEntrenar(int idInt, Entrenamiento entrenamiento, Date fecha, int valor, int incorrecto, Set fichaPreguntas) {
       this.idInt = idInt;
       this.entrenamiento = entrenamiento;
       this.fecha = fecha;
       this.valor = valor;
       this.incorrecto = incorrecto;
       this.fichaPreguntas = fichaPreguntas;
    }
   
    public int getIdInt() {
        return this.idInt;
    }
    
    public void setIdInt(int idInt) {
        this.idInt = idInt;
    }
    public Entrenamiento getEntrenamiento() {
        return this.entrenamiento;
    }
    
    public void setEntrenamiento(Entrenamiento entrenamiento) {
        this.entrenamiento = entrenamiento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public int getIncorrecto() {
        return this.incorrecto;
    }
    
    public void setIncorrecto(int incorrecto) {
        this.incorrecto = incorrecto;
    }
    public Set getFichaPreguntas() {
        return this.fichaPreguntas;
    }
    
    public void setFichaPreguntas(Set fichaPreguntas) {
        this.fichaPreguntas = fichaPreguntas;
    }




}


