package Pojo;
// Generated 26/06/2015 06:18:16 PM by Hibernate Tools 3.6.0



/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idPregunta;
     private Test test;
     private Concepto concepto;
     private String descripcion;
     private double peso;

    public Pregunta() {
    }

    public Pregunta(int idPregunta, Test test, Concepto concepto, String descripcion, double peso) {
       this.idPregunta = idPregunta;
       this.test = test;
       this.concepto = concepto;
       this.descripcion = descripcion;
       this.peso = peso;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPeso() {
        return this.peso;
    }
    
    public void setPeso(double peso) {
        this.peso = peso;
    }




}


