package Pojo;
// Generated 23/07/2015 06:24:00 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Resultado generated by hbm2java
 */
public class Resultado  implements java.io.Serializable {


     private Integer idResultado;
     private Test test;
     private Estudiante estudiante;
     private Date fechaResultado;

    public Resultado() {
    }

    public Resultado(Test test, Estudiante estudiante, Date fechaResultado) {
       this.test = test;
       this.estudiante = estudiante;
       this.fechaResultado = fechaResultado;
    }
   
    public Integer getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(Integer idResultado) {
        this.idResultado = idResultado;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Date getFechaResultado() {
        return this.fechaResultado;
    }
    
    public void setFechaResultado(Date fechaResultado) {
        this.fechaResultado = fechaResultado;
    }




}


