package Pojo;
// Generated 24/07/2015 12:27:41 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private int idTest;
     private Tema tema;
     private Set preguntas = new HashSet(0);
     private Set resultados = new HashSet(0);

    public Test() {
    }

	
    public Test(int idTest, Tema tema) {
        this.idTest = idTest;
        this.tema = tema;
    }
    public Test(int idTest, Tema tema, Set preguntas, Set resultados) {
       this.idTest = idTest;
       this.tema = tema;
       this.preguntas = preguntas;
       this.resultados = resultados;
    }
   
    public int getIdTest() {
        return this.idTest;
    }
    
    public void setIdTest(int idTest) {
        this.idTest = idTest;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }
    public Set getResultados() {
        return this.resultados;
    }
    
    public void setResultados(Set resultados) {
        this.resultados = resultados;
    }




}


