package Pojo;
// Generated 22/07/2015 07:29:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private int idTest;
     private int temaTest;
     private Set preguntas = new HashSet(0);

    public Test() {
    }

	
    public Test(int idTest, int temaTest) {
        this.idTest = idTest;
        this.temaTest = temaTest;
    }
    public Test(int idTest, int temaTest, Set preguntas) {
       this.idTest = idTest;
       this.temaTest = temaTest;
       this.preguntas = preguntas;
    }
   
    public int getIdTest() {
        return this.idTest;
    }
    
    public void setIdTest(int idTest) {
        this.idTest = idTest;
    }
    public int getTemaTest() {
        return this.temaTest;
    }
    
    public void setTemaTest(int temaTest) {
        this.temaTest = temaTest;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }




}


