package Pojo;
// Generated 22/07/2015 06:58:23 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Testemparejamiento generated by hbm2java
 */
public class Testemparejamiento  implements java.io.Serializable {


     private int idEntrena;
     private int error;
     private int tiempo;
     private int puntaje;
     private Date fecha;
     private Set interrogacions = new HashSet(0);

    public Testemparejamiento() {
    }

	
    public Testemparejamiento(int idEntrena, int error, int tiempo, int puntaje, Date fecha) {
        this.idEntrena = idEntrena;
        this.error = error;
        this.tiempo = tiempo;
        this.puntaje = puntaje;
        this.fecha = fecha;
    }
    public Testemparejamiento(int idEntrena, int error, int tiempo, int puntaje, Date fecha, Set interrogacions) {
       this.idEntrena = idEntrena;
       this.error = error;
       this.tiempo = tiempo;
       this.puntaje = puntaje;
       this.fecha = fecha;
       this.interrogacions = interrogacions;
    }
   
    public int getIdEntrena() {
        return this.idEntrena;
    }
    
    public void setIdEntrena(int idEntrena) {
        this.idEntrena = idEntrena;
    }
    public int getError() {
        return this.error;
    }
    
    public void setError(int error) {
        this.error = error;
    }
    public int getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(int tiempo) {
        this.tiempo = tiempo;
    }
    public int getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(int puntaje) {
        this.puntaje = puntaje;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getInterrogacions() {
        return this.interrogacions;
    }
    
    public void setInterrogacions(Set interrogacions) {
        this.interrogacions = interrogacions;
    }




}


